### ISSUE TITLE
No Dynamic List of Colleges.

### ISSUE THREAD

**Issue by sriranganathan** [kousiksatish/f16_scoreboard#2]
## The list of Colleges is just static. There is no way a new college can be added.

In the update page where i can update the scoreboard there is drop down list of colleges. If I select the college as <b>"Others"</b> the app is just storing the <b>college_id as 1</b> which corresponds to  "Others". Shouldn't it <b>accept a college name if the option was "Others"</b> and store it in the colleges table so that the college can be shown in the drop down list for future updates?

**Comment by kousiksatish** [comment]
There is an issue if we give access to people to add colleges. They might not notice the existing colleges from choices properly and add new colleges. So, I felt that it is better if they need us to add new colleges we do it, instead of them adding it directly.

**Comment by sriranganathan** [comment]
Then its better that the option "Others" be removed from the drop down list because it can cause a lot of confusion.
